CREATE TABLE STUDENT (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "SURNAME" VARCHAR(30),
    "NAME" VARCHAR(30)
);

CREATE TABLE THESIS (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "AUTHORID" BIGINT REFERENCES STUDENT(ID),
    "NAME" VARCHAR(255),
    "TYPE" VARCHAR(10), 
    "YEAROFPUBLICATION" INTEGER   
);